### ISSUE TITLE
TypeError: o.shift is not a function

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#1036]
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/504/

```
TypeError: o.shift is not a function
  at apply (./node_modules/jquery/dist/jquery.js:5481:27)
  at apply (./node_modules/jquery/dist/jquery.js:5233:27)
  at apply (./node_modules/jquery/dist/jquery.js:5040:28)
  at HTMLInputElement.d (raven.js:445:21)
```

**Comment by jeanbaptistemora** [comment]
https://trello.com/c/wzBMXo7k
