### ISSUE TITLE
ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#271]
![2018-04-09-201322_513x959_scrot](https://user-images.githubusercontent.com/94636/38514844-a11bcae8-3c32-11e8-832b-ee094a552de2.png)
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/97/

```
ReferenceError: $ is not defined
  at None (./src/mrs/static/js/mrsrequest.js:232:1)
  at __webpack_require__ (webpack/bootstrap 23f652cbece65a0e6bfd:19:1)
  at None (./src/mrs/static/js/base.js:10:1)
  at __webpack_require__ (webpack/bootstrap 23f652cbece65a0e6bfd:19:1)
  at None ((webpack)/buildin/amd-options.js:2:1)
...
(3 additional frame(s) were not displayed)
```

Diag: script loading race condition

**Comment by jpic** [comment]
On a HaiChen qui ajoute le support mobile browser sur le script upload.js, ce qui remplacera jquery-fileupload, source principale de ces erreurs, et l'upload sera tout dans le bundle webpack.
Quand c'est fait, je degage aussi les scripts materialize de django-material pour les charger dans le bundle.
Enfin dans le bundle pour le reste des scripts on chargera jquery via npm, et on aura plus que 1 seul bundle, et l'issue disparaitra ;)
