### ISSUE TITLE
TypeError: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#560]
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/312/

ajouter classes sur les appels a la fonction M.Toast()

```
TypeError: Unable to get property 'length' of undefined or null reference
  at value (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:57338)
  at i (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:57153)
  at M.toast (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:60797)
  at value (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:474002)
  at t.prototype.connect (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:312631)
...
(15 additional frame(s) were not displayed)
```

**Comment by jpic** [comment]
On passe bien l'option de classes dans les appels a Toast du form controller:

https://github.com/yourlabs/crudlfap/blob/9c2e1fd8618bb306fb5cf3803767c61d1581a7c8/js/controllers/form_controller.js

Sur les messages on les reprend des elements de message:

https://github.com/yourlabs/crudlfap/blob/a9f9453d820dda70ca02d4453c1302221a2ca189/js/controllers/messages_controller.js

Qui proviennent d'ici:

https://github.com/yourlabs/crudlfap/blob/9c2e1fd8618bb306fb5cf3803767c61d1581a7c8/src/crudlfap/jinja2/crudlfap/_messages.html

On constate que ces elements n'ont pas toujours de classe, selon leur "level", peut-être qu'une classe par défaut règlerait ce problème, faute de bugfix upstream.
