### ISSUE TITLE
TypeError: i.default(...).getComputedStyle(...) is null

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#565]
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/305/

viewerjs dans la trace sur la page de stat, un controlleur qui se declenche la ou on ne l'attendait pas ?

```
TypeError: i.default(...).getComputedStyle(...) is null
  at r (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:329577)
  at e.default (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:21:329427)
  at t.prototype.getParentHeight (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:31:173367)
  at t.prototype.getCurrentHeight (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:31:172052)
  at t.prototype.updateSizes (/static/webpack_bundles/crudlfap.6fbfeec7b1d6f90c4676.js:31:27270)
...
(30 additional frame(s) were not displayed)
```

**Comment by jpic** [comment]
j'ai trouvé le discord stimulusjs, il faut que j'en parle aec les devs
