### ISSUE TITLE
NS_ERROR_UNEXPECTED

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#582]
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/314/

Wrapper le link prefetch dans un try/catch: pas la peine de remonter a sentry pour une erreur reseau

```
NS_ERROR_UNEXPECTED: 
  at value (/static/webpack_bundles/crudlfap.51f122b78bc8a7305064.js:30:25219)
  at t (/static/webpack_bundles/crudlfap.51f122b78bc8a7305064.js:30:24818)
  at value (/static/webpack_bundles/crudlfap.51f122b78bc8a7305064.js:21:479011)
  at r</t.prototype.connect (/static/webpack_bundles/crudlfap.51f122b78bc8a7305064.js:21:312631)
  at o</t.prototype.connectContextForScope (/static/webpack_bundles/crudlfap.51f122b78bc8a7305064.js:21:404469)
...
(23 additional frame(s) were not displayed)
```

**Comment by jpic** [comment]
https://github.com/getsentry/sentry/issues/10210

**Comment by Johan1983** [comment]
code buggé delete. On close
