### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "mrsstat_stat_date_caisse_id_institution_id_538fe0...

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#618]
https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/333/

Il semblerait que ce soit un cas de race condition entre deux taches de recalcul, dans ce code:

https://github.com/betagouv/mrs/blob/master/src/mrsstat/models.py#L230-L234

Pour trigger le recalcul des champs dénormalisés, il suffit d'appeler save(). Donc, le code requete la stat correspondante, si elle n'existe pas il l'instancie, et dans tous les cas il save() après.

On est toujours dans une transaction (Django crée une transaction par requette HTTP, le spooler reproduit pour encapsuler le callback dans les mêmes conditions que Django (comme dans les autres sources de spoolers que j'ai trouvé)) : https://github.com/yourlabs/django-call/blob/master/djcall/models.py#L293-L310

En l'occurrence, la tache de spool ayant pété une exception, le spooler a du faire un retry, hors de la race condition cela a du se solder par une update.

Conclusion: aucun impact a priori pour cette exception.

Question: quelle est la meilleure approche pour éviter que cela remonte en sentry ?

Piste possible : a voir si django-denorm fonctionne aussi avec update_or_create, auquel cas on pourrait eviter de faire ce filter() suivi de save().

Autre suggestion ?

```
IntegrityError: duplicate key value violates unique constraint "mrsstat_stat_date_caisse_id_institution_id_538fe089_uniq"
DETAIL:  Key (date, caisse_id, institution_id)=(2018-06-05, 9, b3dd8be1-3bbe-4b83-aaf6-4beb982add36) already exists.

  File "django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)

IntegrityError: duplicate key value violates unique constraint "mrsstat_stat_date_caisse_id_institution_id_538fe089_uniq"
DETAIL:  Key (date, caisse_id, institution_id)=(2018-06-05, 9, b3dd8be1-3bbe-4b83-aaf6-4beb982add36) already exists.

(13 additional frame(s) were not displayed)
...
  File "djcall/models.py", line 51, in spooler
    call.call()
  File "djcall/models.py", line 289, in call
    self.result = self.caller.python_callback_call()
  File "djcall/models.py", line 201, in python_callback_call
    return self.python_callback(**self.kwargs)
  File "mrsstat/models.py", line 234, in update_stat_for_mrsrequest
    get_or_create_stat(institution=m.institution, caisse=m.caisse)
  File "mrsstat/models.py", line 228, in get_or_create_stat
    stat.save()

IntegrityError: duplicate key value violates unique constraint "mrsstat_stat_date_caisse_id_institution_id_538fe089_uniq"
DETAIL:  Key (date, caisse_id, institution_id)=(2018-06-05, 9, b3dd8be1-3bbe-4b83-aaf6-4beb982add36) already exists.

```

**Comment by jpic** [comment]
Deuxieme occurrence en production : https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/413/?environment=production

Confirmé que c'est du a une race-condition:

```
mrsstat.models.update_stat_for_mrsrequest(pk=f2e0dc5c-297b-4d) -> Call(id=41950).call(): success
mrsstat.models.update_stat_for_mrsrequest(pk=f2e0dc5c-297b-4d) -> Call(id=41951).call(): exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "mrsstat_stat_date_caisse_id_institution_id_538fe089_uniq"
DETAIL:  Key (date, caisse_id, institution_id)=(2018-12-04, 32, e733ffac-f996-4c2b-a29c-b4fc72833948) already exists.
```

A noter que le spooler a bien recommencé la tache est qu'elle est passée la seconde fois:

```
mrsstat.models.update_stat_for_mrsrequest(pk=25d85796-d84f-43) -> Call(id=41953).call(): success
mrsstat.models.update_stat_for_mrsrequest(pk=25d85796-d84f-43) -> Call(id=41952).call(): success
mrsstat.models.update_stat_for_mrsrequest(pk=f2e0dc5c-297b-4d) -> Call(id=41951).call(): success
```

Aucun probleme bloquant donc.
