### ISSUE TITLE
Sourcemaps en prod

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#638]
Une piste en cours depuis un moment, mais ce qui se passe depuis un moment c'est qu'en fait webpack ne fait plus les sourcemaps du tout quand on est pas en mode local. Le reste de la pipeline concernant sentry fonctionne a ce que j'ai trouve jusqu'ici, c'est juste qu'il faut que webpack build les sourcemaps en mode prod. Je suis donc plus tres loin du denouement.

**Comment by jpic** [comment]
En fait ce bug etait deja fixe, on ne voie pas cependant les sourcemaps dans les artifacts de release sentry.
Cela dit, c'est peut etre normal car les sourcemaps sont a part en sentry.
J'essaye de trigger un event sentry depuis le front sur jpic pour en avoir le coeur net

**Comment by jpic** [comment]
```
00:48:27 [ERROR] sentry.lang.javascript.processor: [Errno 2] No such file or directory: u'/var/lib/sentry/files/17819/1960/33db1b01c35d43e2809231b1057fe389'
Traceback (most recent call last):     
  File "/usr/local/lib/python2.7/site-packages/sentry/lang/javascript/processor.py", line 248, in fetch_release_file
    with releasefile.file.getfile() as fp:                                     
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 208, in getfile
    impl = self._get_chunked_blob(mode, prefetch)                              
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 194, in _get_chunked_blob
    delete=delete                      
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 339, in __init__
    self.open()                        
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 376, in open
    self.seek(0)                       
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 430, in seek
    self._nextidx()                    
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 362, in _nextidx
    self._curfile = self._curidx.blob.getfile()                                
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 160, in getfile
    return storage.open(self.path)     
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 33, in open
    return self._open(name, mode)      
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 159, in _open
    return File(open(self.path(name), mode))                                   
IOError: [Errno 2] No such file or directory: u'/var/lib/sentry/files/17819/1960/33db1b01c35d43e2809231b1057fe389'
00:48:27 [ERROR] sentry.lang.javascript.processor: [Errno 2] No such file or directory: u'/var/lib/sentry/files/17819/1960/33db1b01c35d43e2809231b1057fe389'
```

charmante traceback, on dirait qu'il essaye, je regle un volume

**Comment by jpic** [comment]
apparament il ne recup pas le project id 
```
ERROR:  duplicate key value violates unique constraint "sentry_commitauthor_organization_id_3cdc85e9f09bf3f3_uniq"
DETAIL:  Key (organization_id, external_id)=(1, github:jpic) already exists.
STATEMENT:  UPDATE "sentry_commitauthor" SET "external_id" = 'github:jpic' WHERE "sentry_commitauthor"."id" = 7 
ERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_f0a7ec9ba96de76"
DETAIL:  Key (organization_id, version)=(1, 7909be3b46a23707c1c1376b16331966cea29340) already exists.
STATEMENT:  INSERT INTO "sentry_release" ("organization_id", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id") VALUES (1, NULL, '7909be3b46a23707c1c1376b16331966cea29340', NULL, NULL, '2018-10-15 02:01:06.406614+00:00', NULL, NULL, '{}', 0, NULL, NULL, NULL, '{}', NULL, NULL) RETURNING "sentry_release"."id"
ERROR:  duplicate key value violates unique constraint "sentry_release_project_project_id_35add08b8e678ec7_uniq"
DETAIL:  Key (project_id, release_id)=(4, 907) already exists.
STATEMENT:  INSERT INTO "sentry_release_project" ("project_id", "release_id", "new_groups") VALUES (4, 907, 0) RETURNING "sentry_release_project"."id"
```

**Comment by jpic** [comment]
J'ai fais un script qui marche : https://yourlabs.io/oss/playlabs/blob/master/bin/sentry-release

Malheureusement il faut l'executer pendant la phase de migrate. Je ne sais pas pk sentry a tout base sur le fait qu'on allait builder sur l'environnement final :'(

Reste a trouver comment l'executer au moment du migrate du coup.
